backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Tech", "Crypto", "HR", "Content Writing", "Digital Marketing", "Education"]}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}